// Generated by CoffeeScript 1.3.3
(function() {
  var fill, theBait, theSwitch, _ref;

  theBait = 1000;

  theSwitch = 0;

  _ref = [theSwitch, theBait], theBait = _ref[0], theSwitch = _ref[1];

  fill = function(cont, li) {
    if (li == null) {
      li = "cof";
    }
    return "sdf" + cont;
  };

}).call(this);
